protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		//$this->render('index');
            
                $this->redirect(array('test'));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login()){
				
				$hak = Yii::app()->user->role;
				
				if($hak === 'bidan')
					$this->redirect(array('/bidan'));
				
				if($hak === 'pemda')
					$this->redirect(array('/pemda'));
				
				if($hak === 'admin')
					$this->redirect(array('kandidatbayi/index'));
				
			}
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
	
	/**
	*
	*/
	public function actionFindBidan(){
		$q = new CDbCriteria();
		$request = trim($_GET['term']);
		if($request != ''){
			$q->addSearchCondition('nama', $request);
			$model = Bidan::model()->findAll($q);
			
			$data = array();
                        if (!empty($model)){
                            foreach($model as $get){
                                    $data[] = array(
                                            'nik'=>$get->nik,
                                            'nama'=>$get->nama,
                                            'alamat'=>$get->alamat
                                    );
                            }
                            //echo CJSON::encode($data);
                        } else {
                            $data[] = array(
                                'nik'=>'0',
                                'nama'=>'Data tidak ditemukan,',
                                'alamat'=>'periksa kembali kata kunci yang diinputkan'
                            );
                        }
                        echo CJSON::encode($data);
		}
	}
	
	/**
	*
	*/
	public function actionFindKK(){
		
		if(isset($_POST['KandidatBayi']['no_kk'])){
			$nokk = $_POST['KandidatBayi']['no_kk'];
			$model = DataKeluarga::model()->findByPK($nokk);
			if($model != null){
				$ayah = BiodataWni::model()->findByAttributes(array('no_kk'=>$nokk,'nama_lgkp'=>$model->nama_kep));
				echo json_encode($ayah->attributes);
			} else {
				echo 'data not found';
			}
		} else
			echo 'no data sent';
	}
	
	/**
	*
	*/
	public function actionFindNama(){
		if(isset($_POST['nik'])){
			$nik = $_POST['nik'];
			$model = BiodataWni::model()->findByPK($nik);

			echo $model->nama_lgkp;
		} else{
			echo 'no data send';
		}
	}
	
	/**
	*
	*/
	public function actionDaftar(){
		$this->layout = '//layouts/column2';
		
		$pengajuan = new Pengajuan;
		$bayi = new KandidatBayi;
		$pelapor = new DetailPelapor;
		
		if(isset($_POST['Pengajuan'], $_POST['KandidatBayi'])){
			$pengajuan->ad_id = 1;
			$pengajuan->nik = $_POST['Pengajuan']['nik'];
			$pengajuan->umur_kehamilan = $_POST['Pengajuan']['umur_kehamilan'];
			$pengajuan->tanggal_pengajuan = date('Y-m-d');
			$pengajuan->insert_datetime = date('Y-m-d');
			$pengajuan->insert_by = 'masyarakat';
			$pengajuan->update_datetime = NULL;
			$pengajuan->update_by = NULL;
			$pengajuan->status_id = 1;
            if ($pengajuan->save()){
				// status history object, fill with data and save
				$stathistory = new StatusPengajuanHistory;
				$stathistory->pengajuan_id = $pengajuan->pengajuan_id;
				$stathistory->status_id = $pengajuan->status_id;
				$stathistory->insert_by = $pengajuan->insert_by;
				$stathistory->insert_datetime = $pengajuan->tanggal_pengajuan;
				$stathistory->save(false);
						
				//checklist persyaratan pengajuan, fill with data and save
				$cpp = new ChecklistPersyaratanPengajuan;
				$cpp->pengajuan_id = $pengajuan->pengajuan_id;
				$cpp->pa_id = 1;
				$cpp->kuantitas = 2;
				if ($pengajuan->status_id == 2){
					$cpp->isQualified = 1;
				} else {
					$cpp->isQualified = 0;
				}
				$cpp->save();
				
				$bayi->pengajuan_id = $pengajuan->pengajuan_id;
				$bayi->attributes = $_POST['KandidatBayi'];
				$bayi->nik_bayi = null;
				$bayi->sk_id = 1;
				$bayi->insert_datetime = date('Y-m-d');
				$bayi->insert_by = 'masyarakat';
				if($bayi->save()){
					$kandidatHist = new StatusKandidatHistory;
					$kandidatHist->kandidat_id = $bayi->kandidat_id;
					$kandidatHist->sk_id = $bayi->sk_id;
					$kandidatHist->insert_datetime = $bayi->insert_datetime;
					$kandidatHist->insert_by = $bayi->insert_by;
					$kandidatHist->save(false);
					
					$pelapor->kandidat_id = $bayi->kandidat_id;
					$pelapor->nik = $bayi->nik_pelapor;
					$pelapor->tanggal_lapor = date('Y-m-d');
					$pelapor->hubungan_keluarga = $_POST['DetailPelapor']['hubungan_keluarga'];
					var_dump($pelapor->attributes);
					$pelapor->save(false);
					
					Yii::app()->user->setFlash('success','Data Telah terkirim, Silahkan kunjungi bidan anda untuk informasi lebih lanjut. Terima Kasih');
				}
			}
		}
		
		$this->render('daftar',array('pengajuan'=>$pengajuan,'bayi'=>$bayi,'pelapor'=>$pelapor));
	}
	
	public function actionTest(){
		$this->layout = '//layouts/column';
                $this->render('index_new');
	}
        
        
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main_login'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2 - Copy.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<!--
<div class="span-5 last">
	<div id="sidebar">
	<?php
		/*$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Menu',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>array(
				array('label'=>'Pendaftaran', 'url'=>array('/pengajuan/create')),
				array('label'=>'List Calon Bayi', 'url'=>array('/kandidatbayi/index')),
				array('label'=>'Rekapitulasi Calon Bayi', 'url'=>array('/kandidatbayi/rekap')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
			'htmlOptions'=>array('class'=>'Menu'),
		));
		$this->endWidget(); */
	?>
	</div>
</div>
-->

<div class="content">
	<div id='container'>
		<?php echo $content; ?>
	</div>
</div><!-- content -->

<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php 
	$this->beginContent('//layouts/main'); 
	if(!isset($model)){ $model=new LoginForm; }
?>

<section id="content">
	<div class="container">
		<div class="row">
			<div class="col-md-3 col-sm-3">
				<div id="side-menu" class="list-group">
                                    <a class="list-group-item header" href="#login">
                                        <center>&nbsp;Menu</center>
                                    </a>
                                        <a class="list-group-item" href="<?php echo Yii::app()->createUrl('/site/daftar');?>">
						<i class="fa fa-bars"></i> &nbsp;Pendaftaran
					</a>
					<a class="list-group-item header" data-toggle="collapse" data-parent="#accordion" href="#login">
						<i class="fa fa-user"></i> &nbsp;Login
					</a>
					<div id="login" class="panel-collapse collapse in">
						<div class="list-group-item">
							<div class="form">
								<?php echo CHtml::beginForm(Yii::app()->createUrl('/site/login'),'POST');?>
									<div class="form-group">
										<?php echo CHtml::activeLabel($model,'username',array('label'=>'Username'));?>
										<?php echo CHtml::activeTextField($model,'username',array('class'=>'form-control','placeholder'=>'username'));?>
									</div>
									<div class="form-group">
										<?php echo CHtml::activeLabel($model,'password',array('label'=>'Password'));?>
										<?php echo CHtml::activePasswordField($model,'password',array('class'=>'form-control','placeholder'=>'Password'));?>
									</div>
									<div class="checkbox">
										<label>
											<?php echo CHtml::activeCheckBox($model,'rememberMe'); ?>
											<?php echo CHtml::activeLabel($model,'rememberMe'); ?>
										</label>
									</div>
									<?php echo CHtml::submitButton('Login',array('class'=>'btn btn-primary')); ?>
								<?php echo CHtml::endForm(); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-9 col-sm-9 left">
				<?php echo $content; ?>
			</div>
		</div>
	</div>
</section>

<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>

<?php 
	$activePage = $this->getAction()->controller->action->id;
?>

<?php if(!isset($model)){ $model=new LoginForm; }?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title><?php echo CHtml::encode($this->pageTitle); ?></title>
		<link href="<?php echo Yii::app()->request->baseUrl;?>/css/font-awesome.min.css" rel="stylesheet" >
		<link href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.min.css" rel="stylesheet">
		<link href="<?php echo Yii::app()->request->baseUrl; ?>/css/datepicker.css" rel="stylesheet">
		<link href="<?php echo Yii::app()->request->baseUrl; ?>/css/siakte.css" rel="stylesheet">
	</head>
	
	<body>
		<div id="wrapper">
			<header>
				<div id="line-header"></div>
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							Header
						</div>
					</div>
				</div>
			</header>
			
			<?php echo $content; ?>
			<!-- Content -->
			
			<footer>
				<div class="container">
					<div class="row">
						<div class="col-md-* col-sm-* no-padding">
							<center>&copy; Copyright 2014 - 2020 Disduk Capil. <br /> All Rights Reserved</center>
						</div>
					</div>
				</div>
			</footer>
		</div>
		
		<div class="device-xs visible-xs"></div>
		<div class="device-sm visible-sm"></div>
		<div class="device-md visible-md"></div>
		
		<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery-1.10.2.min.js"></script>
		<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap.min.js"></script>
		<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap-datepicker.js"></script>
		<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/siakte.js"></script>
	</body>
</html>

protected/views/layouts/main_login.php
<?php /* @var $this Controller */ ?>
<?php Yii::app()->bootstrap->register(); //load bootstrap?>

<!DOCTYPE html">
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />
	
	<!-- blueprint CSS framework -->
	<!--
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.min.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	-->
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->
	<!-- 
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
	-->
	
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

	<body class='layout-main'>

		<!--<div class="container" id="page"> -->	
		<!-- header 
		<div id="header">
			<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
		</div>
		-->
		
		<!-- Navbar -->
		<?php /*
			$this->widget('bootstrap.widgets.TbNavbar', array(
				//'brandLabel' => 'Title',
				'display' => null, // default is static to top
				'items' => array(
					array(
						'class' => 'bootstrap.widgets.TbNav',
						'items' => array(
							array('label'=>'Pendaftaran', 'url'=>array('/pengajuan/create')),
							array('label'=>'List Calon Bayi', 'url'=>array('/kandidatbayi/index')),
							array('label'=>'Rekapitulasi Calon Bayi', 'url'=>array('/kandidatbayi/rekap')),
						),
					),
					array(
						'class' => 'bootstrap.widgets.TbNav',
						'items' => array(
							TbHtml::navbarMenuDivider(),
							array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
							array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest),
						),
						'htmlOptions'=>array(
							'class'=>'pull-right',
						),
					),
				),
			)); 
		*/?>
		<!-- End Navbar -->
		
		<!-- Content -->
		<?php echo $content; ?>
		<!-- End Content -->

		<!-- Footer -->
		<footer class='footer' style='text-align: center;'>
			<div class='container'>
				Copyright &copy; <?php echo date('Y'); ?> by Dinas Kependudukan dan Pencatatan Sipil.<br/>
				Kabupaten Padang Pariaman<br/>
				All Rights Reserved.<br/>
			</div>
		</footer>
	</body>
</html>

protected/views/layouts/main_new.php
<?php
    
    
?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
        <link href="<?php echo Yii::app()->request->baseUrl;?>/css/font-awesome.min.css" rel="stylesheet" >
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <link href="<?php echo Yii::app()->request->baseUrl;?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo Yii::app()->request->baseUrl;?>/css/siakcapil_new.css" rel="stylesheet">
    </head>

    <body>
	<!---------------[ header ]---------------------------------------------------------------------------------------------->
	<header>
            <div class="container">
                <a href="index.php" class="logo">
                    <div class="image">
                        <img src="<?php echo Yii::app()->request->baseUrl;?>/images/logo.png" />
                    </div>
                    <div class="text">
                        <div class="title">ACE</div>
                        <div class="sub-title">Administrasi Cepat Elektronik</div>
                    </div>
                </a>
                <div class="right-group">
                    <div class="xrow">
                        <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#LoginModal"><i class="fa fa-lock"></i> Login</button>
                        <span class="hidden-xs"><i class="fa fa-phone"></i> <span style="color: #ff8b00;">Call Center</span>  021-8093008</span>
                    </div>
                    <div class="xrow hidden-xs">
                        <span>
                            <a href="#"><span class="round-icon"><i class="fa fa-twitter"></i></span></a>&nbsp;
                            <a href="#"><span class="round-icon"><i class="fa fa-facebook"></i></span></a>
                        </span>
                        <form class="search-box-1">
                            <input type="text" placeholder="Search..." />
                            <button type="submit"><i class="fa fa-search"></i></button> 
                        </form>
                    </div>
                </div>
            </div>
	</header>
	
	<!----------------------[ Login Modal ]------------------------------------------------------------------------------------------------------>
	<div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <center><h4 class="modal-title"><i class="fa fa-sign-in"></i> Login</h4></center>
                    </div>
                    <div class="modal-body">
                        <form class="form-group login-form" action="<?php echo Yii::app()->createUrl('/site/login')?>" method="POST">
                            <div class="icon-input">
                                <i class="fa fa-user"></i>
                                <input class="form-control" type="text" placeholder="Username" name="LoginForm[username]"/>
                            </div>		
                            <div class="icon-input">
                                <input class="form-control" type="password" placeholder="Password" name="LoginForm[password]"/>
                                <i class="fa fa-lock"></i>
                            </div>
                            <br/>
                            <center><button type="submit" class="btn btn-primary">Log In</button></center>
                        </form>
                        <center><a class="forgot" href="#">Lupa Password?</a></center>
                    </div>
                    <div class="modal-footer">
                        <center><button type="button" class="btn btn-default" data-dismiss="modal">Close</button></center>
                    </div>
                </div>
            </div>
	</div>
	
        <?php echo $content;?>
        
        <!--------------------[ Footer ]------------------------------------------------------------------------------------->
	<footer>
            <div class="container">
                <br/><br/><br/>
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <h4><b>Menu</b></h4>
                        <div class="row">
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <ul class="footer-menu">
                                    <li><a href="#">Beranda</a></li>
                                    <li><a href="#">Profil</a></li>
                                    <li><a href="#">Produk</a></li>
                                    <li><a href="#">Kantor Regional</a></li>
                                    <li><a href="#">Berita</a></li>
                                </ul>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <ul class="footer-menu">
                                    <li><a href="#">Video</a></li>
                                    <li><a href="#">Regulasi</a></li>
                                    <li><a href="#">SJDI</a></li>
                                    <li><a href="#">Publikasi</a></li>
                                    <li><a href="#">Blog Kepegawaian</a></li>
                                </ul>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <ul class="footer-menu">
                                    <li><a href="#">LPID</a></li>
                                    <li><a href="#">Portal</a></li>
                                    <li><a href="#">Hubungi Kami</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 sep">
                        <h4><b>Call Center</b></h4>
                        <span class="round-icon2"><i class="fa fa-phone"></i></span><span>&nbsp;&nbsp;021-8093008</span>
                        <br/><br/>
                        <h4><b>Kantor Pusat</b></h4>
                        <p>Jl. Letjen Sutoyo No. 12 Telp 021-8093008 Jakarta Timur 13640</p>
                        <br/>
                    </div>
                    <div class="col-md-4 col-sm-4 sep">
                        <h4><b>Follow Kami</b></h4>
                        <span class="round-icon2"><i class="fa fa-facebook"></i></span>&nbsp;&nbsp;<a href="#">malesuada facebook</a><br/>
                        <span class="round-icon2"><i class="fa fa-twitter"></i></span>&nbsp;&nbsp;<a href="#">@olutpatpulvinar_twitter</a>
                        <br/><br/>
                        <h4><b>Subscribe</b></h4>
                        <form class="subscribe form-inline">
                            <input class="form-control input-sm" type="text" placeholder="Email" /><i class="fa fa-envelope-o"></i>
                            <button class="btn btn-black btn-sm" type="submit">Subscribe</button> <br/>
                            <span>Dapatkan Kabar Terbaru dari Kami</span>
                        </form>
                    </div>
                </div>
                <br/><br/><br/>
            </div>
            <div class="copyright">Hak cipta &copy; 2014 Dukcapil. Semua Hak Dilindungi</div>
	</footer>
	<script src="<?php echo Yii::app()->request->baseUrl;?>/js/jquery-1.10.2.min.js"></script>
	<script src="<?php echo Yii::app()->request->baseUrl;?>/js/bootstrap.min.js"></script>
	<script src="<?php echo Yii::app()->request->baseUrl;?>/js/siakcapil_new.js"></script>
    </body>
</html>

protected/views/layouts/main_ori.php
<?php /* @var $this Controller */ ?>
<?php Yii::app()->bootstrap->register(); //load bootstrap?>

<!DOCTYPE html">
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />
	
	<!-- blueprint CSS framework -->
	<!--
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.min.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	-->
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->
	<!-- 
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
	-->
	
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

	<body class='layout-main'>

		<!--<div class="container" id="page"> -->	
		<!-- header 
		<div id="header">
			<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
		</div>
		-->
		
		<!-- Navbar -->
		<?php 
			$this->widget('bootstrap.widgets.TbNavbar', array(
				//'brandLabel' => 'Title',
				'display' => null, // default is static to top
				'items' => array(
					array(
						'class' => 'bootstrap.widgets.TbNav',
						'items' => array(
							array('label'=>'Pendaftaran', 'url'=>array('/pengajuan/create')),
							array('label'=>'List Calon Bayi', 'url'=>array('/kandidatbayi/index')),
							array('label'=>'Rekapitulasi Calon Bayi', 'url'=>array('/kandidatbayi/rekap')),
						),
					),
					array(
						'class' => 'bootstrap.widgets.TbNav',
						'items' => array(
							TbHtml::navbarMenuDivider(),
							array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
							array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest),
						),
						'htmlOptions'=>array(
							'class'=>'pull-right',
						),
					),
				),
			)); 
		?>
		<!-- End Navbar -->
		
		<!-- Content -->
		<?php echo $content; ?>
		<!-- End Content -->

		<!-- Footer -->
		<footer class='footer' style='text-align: center;'>
			<div class='container'>
				Copyright &copy; <?php echo date('Y'); ?> by Dinas Kependudukan dan Pencatatan Sipil.<br/>
				Kabupaten Padang Pariaman<br/>
				All Rights Reserved.<br/>
			</div>
		</footer>
	</body>
</html>

protected/views/layouts/sidebar.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
